version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes_auth
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mydb
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
